name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make clang-format cppcheck
        sudo gem install ceedling

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/STM32_AzureRTOS_Project/build -S ${{github.workspace}}/STM32_AzureRTOS_Project

    - name: Build
      run: make -C ${{github.workspace}}/STM32_AzureRTOS_Project/build

    - name: Run clang-format
      run: clang-format -i ${{github.workspace}}/STM32_AzureRTOS_Project/src/*.c

    - name: Run cppcheck
      run: cppcheck --enable=all --std=c11 --template=gcc --verbose --quiet --error-exitcode=1 ${{github.workspace}}/STM32_AzureRTOS_Project/src/*.c

    - name: Run ceedling tests
      run: |
        cd ${{github.workspace}}/STM32_AzureRTOS_Project/test
        ceedling test:all

