name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        family: [G0]
      fail-fast: false

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Clone STM32CubeG0 Repository
      run: |
        sudo git clone https://github.com/STMicroelectronics/STM32CubeG0.git /opt/STM32CubeG0

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make clang-format cppcheck ninja-build
        sudo gem install ceedling
        sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi

    - name: Create build directory for tests/fetch
      run: cmake -E make_directory ${{github.workspace}}/STM32_AzureRTOS_Project/tests/fetch/build

    - name: Initialize ThreadX Submodule
      run: |
        git submodule update --init --recursive

    - name: Create ThreadX Build Directory
      run: mkdir -p ${{github.workspace}}/STM32_AzureRTOS_Project/drivers/ThreadX/build

    - name: Build ThreadX
      run: |
        cd ${{github.workspace}}/STM32_AzureRTOS_Project/drivers/ThreadX
        cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=./cmake/cortex_m0.cmake -GNinja .
        cmake --build ./build
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/STM32_AzureRTOS_Project/examples/MyGPIO_test/build -S ${{github.workspace}}/STM32_AzureRTOS_Project/examples/MyGPIO_test
      
    - name: Build
      run: make -C ${{github.workspace}}/STM32_AzureRTOS_Project/examples/MyGPIO_test/build

    - name: Run clang-format on examples
      run: find ${{github.workspace}}/STM32_AzureRTOS_Project/examples -name "*.c" -o -name "*.h" -print0 | xargs -0 clang-format -i

    - name: Run clang-format on include
      run: find ${{github.workspace}}/STM32_AzureRTOS_Project/include -name "*.c" -o -name "*.h" -print0 | xargs -0 clang-format -i

    - name: Run clang-format on src
      run: find ${{github.workspace}}/STM32_AzureRTOS_Project/src -name "*.c" -print0 | xargs -0 clang-format -i
      
    - name: Run cppcheck
      run: cppcheck --enable=all --std=c11 --template=gcc --verbose --quiet --error-exitcode=1 ${{github.workspace}}/STM32_AzureRTOS_Project/src/*.c

    - name: Run ceedling tests
      run: |
        cd ${{github.workspace}}/STM32_AzureRTOS_Project
        ceedling test:all
